baseURL = "http://saxsir.me/"
languageCode = "ja-jp"
title = "saxsir.me"
theme = "hugo-xmin"

[permalinks]
    post = "/post/:year/:month/:day/:slug"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"
    weight = 4
[[menu.main]]
    name = "Repository"
    url = "https://github.com/saxsir/saxsir.me"
    weight = 5

[params]
    description = ""
    footer = "&copy; Shohei Sasamoto 2017 | [Github](https://github.com/saxsir) | [Twitter](https://twitter.com/saxsir256)"
